/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author esteb
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        // Setear texto subrayado del link de nuevo usuario
        newUser_link.setText("<html><u> Are you a new user? Register here</u></html>");
        // Escalar icono al JPanel del boton de login
        Image imagen = new ImageIcon(getClass().getResource("/Images/login.png")).getImage(); // Buscar la imagen por su ruta
        ImageIcon icono = new ImageIcon(imagen.getScaledInstance(login_btn.getWidth(), login_btn.getHeight(), Image.SCALE_SMOOTH));
        login_btn.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        app_panel = new javax.swing.JPanel();
        logo_img = new javax.swing.JLabel();
        appName_txt = new javax.swing.JLabel();
        login_panel = new javax.swing.JPanel();
        newUser_link = new javax.swing.JLabel();
        login_txt = new javax.swing.JLabel();
        user_txt = new javax.swing.JLabel();
        enterPass_txtField = new javax.swing.JTextField();
        enterUser_txtField = new javax.swing.JTextField();
        pass_txt = new javax.swing.JLabel();
        login_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        app_panel.setBackground(new java.awt.Color(255, 255, 255));
        app_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        app_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_img.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        logo_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_img.setText("Logo");
        app_panel.add(logo_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 30));

        appName_txt.setFont(new java.awt.Font("Cascadia Code", 0, 16)); // NOI18N
        appName_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appName_txt.setText("App Name");
        app_panel.add(appName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        login_panel.setBackground(new java.awt.Color(255, 255, 255));
        login_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        login_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newUser_link.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        newUser_link.setForeground(new java.awt.Color(0, 51, 204));
        newUser_link.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newUser_link.setText("Are you a new user? Register here");
        newUser_link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_panel.add(newUser_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 330, 40));

        login_txt.setFont(new java.awt.Font("Cascadia Code", 1, 48)); // NOI18N
        login_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_txt.setText("Log In");
        login_panel.add(login_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, 60));

        user_txt.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        user_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_txt.setText("Username");
        login_panel.add(user_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 90, 40));

        enterPass_txtField.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        enterPass_txtField.setForeground(new java.awt.Color(204, 204, 204));
        enterPass_txtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterPass_txtField.setText("enter password");
        enterPass_txtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        enterPass_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterPass_txtFieldActionPerformed(evt);
            }
        });
        login_panel.add(enterPass_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 350, 40));

        enterUser_txtField.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        enterUser_txtField.setForeground(new java.awt.Color(204, 204, 204));
        enterUser_txtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterUser_txtField.setText("enter username");
        enterUser_txtField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        enterUser_txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterUser_txtFieldActionPerformed(evt);
            }
        });
        login_panel.add(enterUser_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 350, 40));

        pass_txt.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        pass_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass_txt.setText("Password");
        login_panel.add(pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 90, 40));

        login_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_panel.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 40, 40));

        app_panel.add(login_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1090, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterPass_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterPass_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterPass_txtFieldActionPerformed

    private void enterUser_txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterUser_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterUser_txtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appName_txt;
    private javax.swing.JPanel app_panel;
    private javax.swing.JTextField enterPass_txtField;
    private javax.swing.JTextField enterUser_txtField;
    private javax.swing.JLabel login_btn;
    private javax.swing.JPanel login_panel;
    private javax.swing.JLabel login_txt;
    private javax.swing.JLabel logo_img;
    private javax.swing.JLabel newUser_link;
    private javax.swing.JLabel pass_txt;
    private javax.swing.JLabel user_txt;
    // End of variables declaration//GEN-END:variables
}
