/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author esteb
 */
public class production extends javax.swing.JFrame {

    /**
     * Creates new form production
     */
    public production() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        production_content = new javax.swing.JPanel();
        return_btn_Production = new javax.swing.JLabel();
        titulo_txt_Production = new javax.swing.JLabel();
        type_txt_Prod = new javax.swing.JLabel();
        releaseDate_txt_Prod = new javax.swing.JLabel();
        rating_txt_Production = new javax.swing.JLabel();
        ratingData_Production = new javax.swing.JLabel();
        userRating_txt_Production = new javax.swing.JLabel();
        userRating_data_Production = new javax.swing.JLabel();
        image_Production = new javax.swing.JLabel();
        trailer_Production = new javax.swing.JLabel();
        moreImg_btn_Production = new javax.swing.JLabel();
        buy_btn_Production = new javax.swing.JLabel();
        addCart_checkBox = new javax.swing.JCheckBox();
        wishlist_checkBox = new javax.swing.JCheckBox();
        episodes_btn_Prod = new javax.swing.JLabel();
        genres_Production = new javax.swing.JLabel();
        synopsis_txt_Production = new javax.swing.JLabel();
        synopsis_scroll = new javax.swing.JScrollPane();
        synopsis_txt = new javax.swing.JTextArea();
        separatingBar_Prod = new javax.swing.JLabel();
        runtime_txt_Production = new javax.swing.JLabel();
        runtime_data_Production = new javax.swing.JLabel();
        platforms_txt_Production = new javax.swing.JLabel();
        platforms_data_Production = new javax.swing.JLabel();
        price_txt_Prod = new javax.swing.JLabel();
        price_data_Prod = new javax.swing.JLabel();
        location_txt_Production = new javax.swing.JLabel();
        location_data_Production = new javax.swing.JLabel();
        director_txt_Production = new javax.swing.JLabel();
        director_data_Production = new javax.swing.JLabel();
        writers_txt_Production = new javax.swing.JLabel();
        writers_list = new javax.swing.JComboBox<>();
        crew_txt_Production = new javax.swing.JLabel();
        crew_list = new javax.swing.JComboBox<>();
        writeReview_txt_Prod = new javax.swing.JLabel();
        star1_Prod = new javax.swing.JLabel();
        star2_Prod = new javax.swing.JLabel();
        star3_Prod = new javax.swing.JLabel();
        star4_Prod = new javax.swing.JLabel();
        star5_Prod = new javax.swing.JLabel();
        userReviews_btn_Prod = new javax.swing.JLabel();
        reviewTitle_Prod = new javax.swing.JLabel();
        reviewTitle_txt = new javax.swing.JTextField();
        review_scroll = new javax.swing.JScrollPane();
        review_txt = new javax.swing.JTextArea();
        postReviewBtn_Prod = new javax.swing.JLabel();
        endBar_Prod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        production_content.setBackground(new java.awt.Color(255, 255, 255));
        production_content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        return_btn_Production.setBackground(new java.awt.Color(255, 255, 255));
        return_btn_Production.setFont(new java.awt.Font("Cascadia Code", 1, 16)); // NOI18N
        return_btn_Production.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        return_btn_Production.setText("return");
        return_btn_Production.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        return_btn_Production.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        return_btn_Production.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                return_btn_ProductionMouseClicked(evt);
            }
        });
        production_content.add(return_btn_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 60));

        titulo_txt_Production.setFont(new java.awt.Font("Cascadia Code", 1, 48)); // NOI18N
        titulo_txt_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo_txt_Production.setText("[Production Title]");
        production_content.add(titulo_txt_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 550, 60));

        type_txt_Prod.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        type_txt_Prod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        type_txt_Prod.setText("ProdType");
        production_content.add(type_txt_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 80, 20));

        releaseDate_txt_Prod.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        releaseDate_txt_Prod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        releaseDate_txt_Prod.setText("releaseDate");
        production_content.add(releaseDate_txt_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 90, 20));

        rating_txt_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        rating_txt_Production.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rating_txt_Production.setText("Rating");
        production_content.add(rating_txt_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 60, 30));

        ratingData_Production.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        ratingData_Production.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratingData_Production.setText("Val");
        production_content.add(ratingData_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, 40, 30));

        userRating_txt_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        userRating_txt_Production.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userRating_txt_Production.setText("Your Rating");
        production_content.add(userRating_txt_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 100, 30));

        userRating_data_Production.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        userRating_data_Production.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userRating_data_Production.setText("Val");
        production_content.add(userRating_data_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 50, 30));

        image_Production.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_Production.setText("MAIN IMAGE");
        image_Production.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        production_content.add(image_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, 210));

        trailer_Production.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trailer_Production.setText("TRAILER");
        trailer_Production.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        production_content.add(trailer_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 380, 210));

        moreImg_btn_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        moreImg_btn_Production.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moreImg_btn_Production.setText("More images");
        moreImg_btn_Production.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        moreImg_btn_Production.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(moreImg_btn_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 100, 50));

        buy_btn_Production.setBackground(new java.awt.Color(255, 255, 255));
        buy_btn_Production.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        buy_btn_Production.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buy_btn_Production.setText("Buy");
        buy_btn_Production.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        buy_btn_Production.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buy_btn_Production.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buy_btn_ProductionMouseClicked(evt);
            }
        });
        production_content.add(buy_btn_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 160, 50));

        addCart_checkBox.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        addCart_checkBox.setText("Add to Cart");
        addCart_checkBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(addCart_checkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 140, -1));

        wishlist_checkBox.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        wishlist_checkBox.setText("Add to Wishlist");
        wishlist_checkBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(wishlist_checkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, 140, -1));

        episodes_btn_Prod.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        episodes_btn_Prod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        episodes_btn_Prod.setText(" Episodes >");
        episodes_btn_Prod.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new java.awt.Color(0, 51, 255)));
        episodes_btn_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(episodes_btn_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 150, 30));

        genres_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        genres_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genres_Production.setText("genres");
        genres_Production.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        production_content.add(genres_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 980, 30));

        synopsis_txt_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        synopsis_txt_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        synopsis_txt_Production.setText("Synopsis:");
        production_content.add(synopsis_txt_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 100, 30));

        synopsis_scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        synopsis_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        synopsis_txt.setEditable(false);
        synopsis_txt.setBackground(new java.awt.Color(255, 255, 255));
        synopsis_txt.setColumns(20);
        synopsis_txt.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        synopsis_txt.setRows(5);
        synopsis_txt.setText("aqui va la sinopsis de la produccion");
        synopsis_txt.setBorder(null);
        synopsis_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        synopsis_txt.setFocusable(false);
        synopsis_txt.setSelectionColor(new java.awt.Color(255, 255, 255));
        synopsis_scroll.setViewportView(synopsis_txt);

        production_content.add(synopsis_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 550, 100));

        separatingBar_Prod.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        separatingBar_Prod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        separatingBar_Prod.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        production_content.add(separatingBar_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 980, 10));

        runtime_txt_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        runtime_txt_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        runtime_txt_Production.setText("Run time:");
        production_content.add(runtime_txt_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 100, 30));

        runtime_data_Production.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        runtime_data_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        runtime_data_Production.setText("runtime data");
        production_content.add(runtime_data_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 130, 30));

        platforms_txt_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        platforms_txt_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        platforms_txt_Production.setText("Platforms:");
        production_content.add(platforms_txt_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 100, 30));

        platforms_data_Production.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        platforms_data_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        platforms_data_Production.setText("platforms data");
        production_content.add(platforms_data_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 130, 30));

        price_txt_Prod.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        price_txt_Prod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        price_txt_Prod.setText("Price:");
        production_content.add(price_txt_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 100, 30));

        price_data_Prod.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        price_data_Prod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        price_data_Prod.setText("price data");
        production_content.add(price_data_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 130, 30));

        location_txt_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        location_txt_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        location_txt_Production.setText("Produced in:");
        production_content.add(location_txt_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 100, 30));

        location_data_Production.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        location_data_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        location_data_Production.setText("location data");
        production_content.add(location_data_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 130, 30));

        director_txt_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        director_txt_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        director_txt_Production.setText("Director:");
        production_content.add(director_txt_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 100, 30));

        director_data_Production.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        director_data_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        director_data_Production.setText("director data");
        production_content.add(director_data_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 690, 130, 30));

        writers_txt_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        writers_txt_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        writers_txt_Production.setText("Writers:");
        production_content.add(writers_txt_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 730, 100, 30));

        writers_list.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        writers_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        production_content.add(writers_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 730, 200, 30));

        crew_txt_Production.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        crew_txt_Production.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        crew_txt_Production.setText("Crew members:");
        production_content.add(crew_txt_Production, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 780, 100, 30));

        crew_list.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        crew_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        production_content.add(crew_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 780, 200, 30));

        writeReview_txt_Prod.setFont(new java.awt.Font("Cascadia Code", 1, 28)); // NOI18N
        writeReview_txt_Prod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        writeReview_txt_Prod.setText("Write your review");
        production_content.add(writeReview_txt_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 870, 310, 30));

        star1_Prod.setFont(new java.awt.Font("Cascadia Code", 0, 10)); // NOI18N
        star1_Prod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star1_Prod.setText("star1");
        star1_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        star1_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(star1_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 910, 40, 40));

        star2_Prod.setFont(new java.awt.Font("Cascadia Code", 0, 10)); // NOI18N
        star2_Prod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star2_Prod.setText("star2");
        star2_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        star2_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(star2_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 910, 40, 40));

        star3_Prod.setFont(new java.awt.Font("Cascadia Code", 0, 10)); // NOI18N
        star3_Prod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star3_Prod.setText("star3");
        star3_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        star3_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(star3_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 910, 40, 40));

        star4_Prod.setFont(new java.awt.Font("Cascadia Code", 0, 10)); // NOI18N
        star4_Prod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star4_Prod.setText("star4");
        star4_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        star4_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(star4_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 910, 40, 40));

        star5_Prod.setFont(new java.awt.Font("Cascadia Code", 0, 10)); // NOI18N
        star5_Prod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star5_Prod.setText("star5");
        star5_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        star5_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(star5_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 910, 40, 40));

        userReviews_btn_Prod.setFont(new java.awt.Font("Cascadia Code", 1, 20)); // NOI18N
        userReviews_btn_Prod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userReviews_btn_Prod.setText(" User reviews >");
        userReviews_btn_Prod.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new java.awt.Color(0, 51, 255)));
        userReviews_btn_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(userReviews_btn_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 910, 200, 30));

        reviewTitle_Prod.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        reviewTitle_Prod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reviewTitle_Prod.setText("Title:");
        production_content.add(reviewTitle_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 920, 50, 30));

        reviewTitle_txt.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        reviewTitle_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewTitle_txtActionPerformed(evt);
            }
        });
        production_content.add(reviewTitle_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 920, 360, 30));

        review_txt.setColumns(20);
        review_txt.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        review_txt.setRows(5);
        review_scroll.setViewportView(review_txt);

        production_content.add(review_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 960, 690, 90));

        postReviewBtn_Prod.setFont(new java.awt.Font("Cascadia Code", 0, 10)); // NOI18N
        postReviewBtn_Prod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        postReviewBtn_Prod.setText("Post");
        postReviewBtn_Prod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        postReviewBtn_Prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        production_content.add(postReviewBtn_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 1010, 60, 40));

        endBar_Prod.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        endBar_Prod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        endBar_Prod.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        production_content.add(endBar_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1070, 1060, 10));

        getContentPane().add(production_content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void return_btn_ProductionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_btn_ProductionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_return_btn_ProductionMouseClicked

    private void buy_btn_ProductionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buy_btn_ProductionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buy_btn_ProductionMouseClicked

    private void reviewTitle_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewTitle_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reviewTitle_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(production.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(production.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(production.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(production.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new production().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addCart_checkBox;
    private javax.swing.JLabel buy_btn_Production;
    private javax.swing.JComboBox<String> crew_list;
    private javax.swing.JLabel crew_txt_Production;
    private javax.swing.JLabel director_data_Production;
    private javax.swing.JLabel director_txt_Production;
    private javax.swing.JLabel endBar_Prod;
    private javax.swing.JLabel episodes_btn_Prod;
    private javax.swing.JLabel genres_Production;
    private javax.swing.JLabel image_Production;
    private javax.swing.JLabel location_data_Production;
    private javax.swing.JLabel location_txt_Production;
    private javax.swing.JLabel moreImg_btn_Production;
    private javax.swing.JLabel platforms_data_Production;
    private javax.swing.JLabel platforms_txt_Production;
    private javax.swing.JLabel postReviewBtn_Prod;
    private javax.swing.JLabel price_data_Prod;
    private javax.swing.JLabel price_txt_Prod;
    private javax.swing.JPanel production_content;
    private javax.swing.JLabel ratingData_Production;
    private javax.swing.JLabel rating_txt_Production;
    private javax.swing.JLabel releaseDate_txt_Prod;
    private javax.swing.JLabel return_btn_Production;
    private javax.swing.JLabel reviewTitle_Prod;
    private javax.swing.JTextField reviewTitle_txt;
    private javax.swing.JScrollPane review_scroll;
    private javax.swing.JTextArea review_txt;
    private javax.swing.JLabel runtime_data_Production;
    private javax.swing.JLabel runtime_txt_Production;
    private javax.swing.JLabel separatingBar_Prod;
    private javax.swing.JLabel star1_Prod;
    private javax.swing.JLabel star2_Prod;
    private javax.swing.JLabel star3_Prod;
    private javax.swing.JLabel star4_Prod;
    private javax.swing.JLabel star5_Prod;
    private javax.swing.JScrollPane synopsis_scroll;
    private javax.swing.JTextArea synopsis_txt;
    private javax.swing.JLabel synopsis_txt_Production;
    private javax.swing.JLabel titulo_txt_Production;
    private javax.swing.JLabel trailer_Production;
    private javax.swing.JLabel type_txt_Prod;
    private javax.swing.JLabel userRating_data_Production;
    private javax.swing.JLabel userRating_txt_Production;
    private javax.swing.JLabel userReviews_btn_Prod;
    private javax.swing.JCheckBox wishlist_checkBox;
    private javax.swing.JLabel writeReview_txt_Prod;
    private javax.swing.JComboBox<String> writers_list;
    private javax.swing.JLabel writers_txt_Production;
    // End of variables declaration//GEN-END:variables
}
